### ISSUE TITLE
v1_21_R1ChunkDataProviderImpl  NullPointerException

### ISSUE THREAD

**Issue by Anresku** [olijeffers0n/PatheticAPI#106]
### Stack trace

Hi, I’m working on one of my personal projects and I needed to find a repo that could save me from the burden of creating my own Pathfinder, and that’s when I found you. After a tough struggle to understand the API since the documentation and code have changed, I managed to make it work—or at least I think I did. However, after structuring the event for my ArmorStand, I got a 'NullPointerException', but I’m not sure if it’s my fault or if there's something wrong in the 'v1_21_R1ChunkDataProviderImpl' class.

I’m sharing the link with my code and the error log below. I also forgot to include how I initialize the API, so I’ll leave that here as a quote.

<details>
<summary>My main class </summary>

```kotlin 
class ItemGuard : JavaPlugin() {
 
     internal val pathfinder = {
         PatheticMapper.newPathfinder(
             PathfinderConfiguration.createConfiguration()
                 .withAllowingFailFast(true)
                 .withAllowingFallback(true)
                 .withLoadingChunks(true)
                 .withBStats(true)
         )
     }
 
     override fun onEnable() {
         
         PatheticMapper.initialize(this)
 
         println("[ItemGuard] initialize pathfinder ${Pathetic.isInitialized()}")
         
         server.pluginManager.registerEvents(PlayerListener(), this)
     }
 
     override fun onDisable() {
         HandlerList.unregisterAll(this)
         server.scheduler.cancelTasks(this)
         Pathetic.shutdown()
     }
 }
```
</details>

### 

> [The code of my event and the log referring to the error](https://paste.gg/p/anonymous/f9005e9524de461699c307cdf8d9f70c)

**Comment by Anresku** [comment]
Update: I found the error, and it seems it was my mistake. I sincerely apologize for creating the issue. I spent over 30 minutes trying to figure it out until I stopped to carefully review everything. In the source, I saw that you had instantiated the "PathEnvironment" by passing the UUID and the world name, and I hadn’t done it that way. I’ll leave the reference code below, and again, I apologize for the inconvenience.


<details>
<summary>Update SupportEvent</summary>

```kotlin
private fun pathPosition(item: Item): Map<String, () -> PathPosition> {
        return mapOf(
            "start" to {
                val location = armorStand.location
                PathPosition(
                    PathEnvironment(ownWorld.uid, ownWorld.name, location.blockY - 20, location.blockY + 20),
                    location.x,
                    location.y,
                    location.z
                )
            },
            "end" to {
                val location = item.location
                PathPosition(
                    PathEnvironment(ownWorld.uid, ownWorld.name, location.blockY - 20, location.blockY + 20),
                    location.x,
                    location.y,
                    location.z
                )
            }
        )
    }
```
</details>

**Comment by bsommerfeld** [comment]
hi, all good, no worries. glad you figured it out! :) 

we appreciate very much that you found to us in the first place, even if the mistake was not with us.

you said you had trouble understanding the API, can you maybe go a little bit more into detail here? we would like to improve and any feedback is welcome and would help us alot!

sincerely,
metaphoriker

**Comment by Anresku** [comment]
Thank you! I’ll leave comments if I find anything. For now, I’m testing and building the logic I need, so along the way, if I find something that could be useful to implement, I’ll mention it. Thanks for the source, so far it seems quite complete.
