### ISSUE TITLE
Problem with documentation for first use

### ISSUE THREAD

**Issue by LukaVerzijl** [olijeffers0n/PatheticAPI#107]
### Stack trace

IDE errors when following docs. Using Latest Release
```
Cannot resolve symbol 'CustomHeightFilter'

Cannot resolve symbol 'EarlyExitFilterStage'

Missing 'PathEnviorment' as ARG 1

location Requires Bukkit.Location, provided PathPosition

```

### Actions to reproduce (if known)

Hi i got these issues when using the latest release, and followings the docs. On a clean project, with no other dependencies. I assume the docs is not accureate with latest releases.

I hope that these errors are just a simple fix of updating the docs.

**Comment by bsommerfeld** [comment]
hi, it seems like you've copied the example from [here](https://github.com/patheloper/pathetic?tab=readme-ov-file#advanced-usage-filtering-and-prioritizing-paths).

that is solely an example and doesn't use actual existing filters. if you want to have an accurate example on how to use pathetic, see the [pathetic-example module](https://github.com/patheloper/pathetic/tree/trunk/pathetic-example).

but you're right, it can be a bit confusing. we will adjust that in the future, thank you!
if you are experiencing any other issues, feel free to share them here :)

**Comment by LukaVerzijl** [comment]
Ah got it thanks for refering to a example code! Got a little confused by that code snippet yea, thanks for letting me know. Il look into the example module now.

**Comment by bsommerfeld** [comment]
nice!

i will close this issue then, thanks for using pathetic and if you have any other questions just open another issue :)
