### ISSUE TITLE
Mapping was not publish to maven

### ISSUE THREAD

**Issue by iarepandemonium** [olijeffers0n/PatheticAPI#14]
Trying to use this on 1.19.4 and your mapping is not published for version 2.1.1, only the api is listed but I need the mapping version

**Comment by iarepandemonium** [comment]
![image](https://user-images.githubusercontent.com/8331173/228005723-255b949c-673f-4467-999f-9c4af0ef72f4.png)

**Comment by olijeffers0n** [comment]
The JitPack build failed. Will investigate shortly

**Comment by olijeffers0n** [comment]
Just JitPack being JitPack. I have deleted the build and rebuilt it. Seems to all be there. LMK if it is fixed

**Comment by iarepandemonium** [comment]
fixed
