### ISSUE TITLE
Simplifying the path finding result

### ISSUE THREAD

**Issue by iarepandemonium** [olijeffers0n/PatheticAPI#15]
I was wondering if it was possible that when a path is moving in a straight line, if there could be an option for a 'simple' version. IE: if Point A, Point B, Point C, Point D all go in the same direction diagonal, we don't really need point B / C if we are trying to use velocity to move an object, we only need a and d, so is is possible to have an option that only gives us A/D?

**Comment by olijeffers0n** [comment]
When you say straight line, do you mean a literal straight line or just imagine raycasting between each point? We are currently moving towards different pathfinder implementations so this could be a possible version. I think i tried this before actually and had some mixed results.

**Comment by iarepandemonium** [comment]
Yea i can get it to do straight straight but i was wondering if you already had this existing bc diagnol is a little more annoying tho i can do it, i just mean if a b c d all are >>>> then i dont need b and c bc my mob is just gonna walk from a to d

**Comment by bsommerfeld** [comment]
currently we don't support that, no. we already have features planned for the future that would make this possible, or achieve exactly that, but it will take a bit until we are at that point.

out of interest: how would you expect this feature being implemented?

**Comment by iarepandemonium** [comment]
Sorry I didn't reply, I don't know how, prolly with an option that defaults to not or something. I implemented in my code by just eliminating anything between two points that were in a straight line.

**Comment by bsommerfeld** [comment]
fyi: we've now implemented a [simplify](https://github.com/patheloper/pathetic/blob/production/pathetic-api/src/main/java/org/patheloper/api/pathing/result/Path.java#L40) method for Path which results in a similar behaviour.

note: its still under test, so we would be glad about feedback. :)
EDIT: available in 2.1.3 and higher

**Comment by iarepandemonium** [comment]
Okay thanks I will check it out soon.
