### ISSUE TITLE
ChunkSnapshot in SnapshotManager is not thread safe. 

### ISSUE THREAD

**Issue by AVolkoff6** [olijeffers0n/PatheticAPI#2]
Whenever the fetchAndGetBlock method is used multiple times at once, it causes errors. 
Thanks for the project by the way, this was tremendously helpful.

**Comment by olijeffers0n** [comment]
Hi, what minecraft version are you running. I think i am aware of this issue on older versions.

**Comment by AVolkoff6** [comment]
I am running 1.18.2, and have the latest code from the repo. SnapshotManagerImpl has a comment at line 48 that reads "// TODO: 27/04/2022 Make this thread safe."

**Comment by olijeffers0n** [comment]
Everything looks to be fixed now. Will close now :)
