### ISSUE TITLE
The FailingSnapshotManager leaks memory

### ISSUE THREAD

**Issue by Sytm** [olijeffers0n/PatheticAPI#22]
The cached chunks in the FailingSnapshotManager.SNAPSHOTS_MAP are only invalidated on block changes but otherwise never discarded.

If a player wanders around the world with constant path finding a lot of ChunkSnapshots accumulate and are never discarded.

**Comment by olijeffers0n** [comment]
Good point, we will switch to a Guava expiring map

**Comment by olijeffers0n** [comment]
Think @GodCipher Has addressed this. Thanks again and let us know if you have any issues!
