### ISSUE TITLE
Ability to cancel an ongoing pathfind

### ISSUE THREAD

**Issue by MCD4U** [olijeffers0n/PatheticAPI#91]
### Is your feature request related to a problem?

I want the ability to cancel a pathfind that was started with `Pathfinder.findPath`. A use case is if I want to pathfind to a location, but for some reason the location became invalid after a short while while the pathfinder is still computing (e.g. sand fell on the location making it impassable). I want to be able to cancel the current pathfind and then start a new pathfind. 

### Describe the solution you'd like.

Whatever is returned from `Pathfinder.findPath` could have a method to cancel it.

### Describe alternatives you've considered.

N/A

**Comment by bsommerfeld** [comment]
Hi, thanks for your suggestion! Yes, you're right, that would probably make a lot of sense, as this is currently only possible via detours or by throwing away the calculated path.

We'll include that, I'll keep you updated here :)

**Comment by bsommerfeld** [comment]
Concluded in [v3.0](https://github.com/patheloper/pathetic/releases/tag/3.0)
